# Generated by Django 3.2.9 on 2022-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20220719_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='issue',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='report',
            field=models.CharField(blank=True, choices=[('1', 'Toxic Behavior '), ('2', 'Bad Service'), ('3', 'Inpropiot Name'), ('4', 'AKF'), ('5', 'Cheat')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='smartContract',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='smartContractGraph',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='star',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='alert',
            field=models.CharField(blank=True, choices=[('1', 'Verified'), ('2', 'Can Be Trusted'), ('3', 'Security Is Low'), ('4', 'Seems Suspicious'), ('5', 'Has Potential Risks')], max_length=500, null=True),
        ),
    ]
