# Generated by Django 3.2.9 on 2022-07-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_djangotest'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangotest',
            name='bigInteger',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangotest',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='djangotest',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djangotest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
