# Generated by Django 3.2.9 on 2022-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20220718_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BigIntegerField(blank=True, null=True)),
                ('dislike', models.BigIntegerField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('shortName', models.CharField(blank=True, max_length=23, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('chain', models.CharField(blank=True, max_length=13, null=True)),
                ('chainId', models.SmallIntegerField(blank=True, null=True)),
                ('networkId', models.SmallIntegerField(blank=True, null=True)),
                ('rpc', models.TextField(blank=True, null=True)),
                ('facets', models.TextField(blank=True, null=True)),
                ('nativeCurrency', models.TextField(blank=True, null=True)),
                ('infoURL', models.URLField(blank=True, null=True)),
                ('slip44', models.IntegerField(blank=True, null=True)),
                ('standard', models.BooleanField(blank=True, null=True)),
                ('ens', models.TextField(blank=True, null=True)),
                ('exprolers', models.TextField(blank=True, null=True)),
                ('hello', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('snapchat', models.URLField(blank=True, null=True)),
                ('discord', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('thanksTo', models.CharField(blank=True, max_length=230, null=True)),
                ('otherProduct', models.TextField(blank=True, null=True)),
                ('supportedPlatform', models.URLField(blank=True, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('helpSupport', models.URLField(blank=True, null=True)),
                ('secured', models.BooleanField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigInteger', models.BigIntegerField(blank=True, null=True)),
                ('binary', models.BinaryField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
                ('char', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('decimal', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('float', models.FloatField(blank=True, null=True)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('images', models.FileField(blank=True, null=True, upload_to='images')),
                ('genericIPAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('positiveInteger', models.PositiveIntegerField(blank=True, null=True)),
                ('positiveSmallInteger', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('smallInteger', models.SmallIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('uRL', models.URLField(blank=True, null=True)),
                ('uUID', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
