# Generated by Django 3.2.9 on 2022-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_blockchain_blockchain_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='secured',
        ),
        migrations.RemoveField(
            model_name='blockchain',
            name='status',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='alert',
            field=models.CharField(blank=True, choices=[('1', 'Verified'), ('2', 'Can Be Trusted'), ('3', 'Security Is Low'), ('4', 'Seems Suspicious'), ('5', 'This Blockchain Has Potential Risks')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='experience',
            field=models.CharField(blank=True, choices=[('1', 'Very Well'), ('2', 'Good'), ('3', 'Can Be Better'), ('4', 'Bad'), ('5', 'Awful')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='supportedPlatform',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
